In [1]:
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn import datasets, svm, cross_validation, tree, preprocessing, metrics
import math
from random import seed
from random import randrange
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


C:\Users\Kotak\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
# ## Load Datasets
df1 = pd.read_csv("processed.va.csv",
                  names= ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"])
t1 = df1.head()
t1.head()

df2 = pd.read_csv("processed.hungarian.csv"
                  ,names= ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"])
t2 = df2.head()
t2.head()

df3 = pd.read_csv("processed.switzerland.csv",
                  names= ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"])
t3 = df3.head()
t3.head()

df4 = pd.read_csv("processed.cleveland.csv",
                  names= ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"])
t4 = df4.head()
t4.head()


age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  num  
0    3.0  0.0  6.0    0  
1    2.0  3.0  3.0    2  
2    2.0  2.0  7.0    1  
3    3.0  0.0  3.0    0  
4    1.0  0.0  3.0    0

In [4]:
# Merge dataframes
frames = [df1, df2, df3, df4]
all4dataset = pd.concat(frames,axis=0, join='outer', join_axes=None, ignore_index=False,keys=None, 
                        levels=None, names=None, verify_integrity=False,copy=True)

# Analyse null values and their counts for each attribute

all4dataset.replace(to_replace="NaN", value="[?]",regex=True, inplace=True)
all4dataset.replace(to_replace="[?]", value=np.nan,regex=True, inplace=True)
all4dataset.isnull().sum()

# Mean and Round the missing values

all4dataset.age.replace(to_replace=np.nan, value=all4dataset['age'].mean(axis=0),regex=True, inplace=True)
all4dataset.sex.replace(to_replace=np.nan, value=round((all4dataset['sex'].mean(axis=0)),0),regex=True, inplace=True)
all4dataset.cp.replace(to_replace=np.nan, value=round((all4dataset['cp'].mean(axis=0)),0),regex=True, inplace=True)

p=all4dataset['trestbps']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.trestbps.replace(to_replace=np.nan, value=mean,regex=True, inplace=True)

p=all4dataset['chol']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.chol.replace(to_replace=np.nan, value=mean,regex=True, inplace=True)

p=all4dataset['fbs']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.fbs.replace(to_replace=np.nan, value=round(mean,0),regex=True, inplace=True)

p=all4dataset['restecg']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.restecg.replace(to_replace=np.nan, value=round(mean,0),regex=True, inplace=True)

p=all4dataset['thalach']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.thalach.replace(to_replace=np.nan, value=mean,regex=True, inplace=True)

p=all4dataset['exang']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.exang.replace(to_replace=np.nan, value=round(mean,0),regex=True, inplace=True)

p=all4dataset['oldpeak']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.oldpeak.replace(to_replace=np.nan, value=mean,regex=True, inplace=True)

p=all4dataset['slope']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.slope.replace(to_replace=np.nan, value=round(mean,0),regex=True, inplace=True)

p=all4dataset['ca']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.ca.replace(to_replace=np.nan, value=round(mean,0),regex=True, inplace=True)

p=all4dataset['thal']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.thal.replace(to_replace=np.nan, value=round(mean,0),regex=True, inplace=True)

p=all4dataset['num']
p=p.fillna('0').as_matrix()
p=p.astype(np.float)
mean=np.mean(p)
all4dataset.num.replace(to_replace=np.nan, value=round(mean,0),regex=True, inplace=True)

all4dataset=all4dataset.astype(float)

In [7]:
X = all4dataset.values[:, 0:12].astype(np.float)
Y = all4dataset.values[:, 13].astype(np.float)
all_data=all4dataset.values[:, :].astype(np.float)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)
#print(X_train)


In [18]:

import warnings
warnings.filterwarnings('ignore')
from hmmlearn.hmm import GaussianHMM

model=GaussianHMM(n_components=5, covariance_type="diag", n_iter=1000).fit(X_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print("HMM accuracy : ",accuracy_score(y_test,y_pred)*100)


[[90 15  7  5  6]
 [26 45  2  3  5]
 [ 7 18  1  3  4]
 [ 6 16  0  1  6]
 [ 2  5  0  1  2]]
HMM accuracy :  50.36231884057971


In [19]:
print("Transition matrix")
print(model.transmat_)


Transition matrix
[[0.4195108  0.36531679 0.04721331 0.04228593 0.12567317]
 [0.47436472 0.3653605  0.03786683 0.06091019 0.06149775]
 [0.5263359  0.20533811 0.07558746 0.04285896 0.14987958]
 [0.50669144 0.25753628 0.02950501 0.12245471 0.08381255]
 [0.49427812 0.33696365 0.02316543 0.04177598 0.10381682]]


In [22]:
# Evaluate an algorithm using a cross validation using k folds
# Calculate accuracy percentage

def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for i in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    folds=dataset_split
    scores = list()
    for fold in folds:
        train_set = list(folds)
        try:
            train_set.remove(fold)
        except ValueError:
            pass 
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        correct = 0
        for i in range(len(actual)):
            if actual[i] == predicted[i]:
                correct += 1
        accuracy = (correct / float(len(actual)) * 100.0)
        scores.append(accuracy)
    return scores

# Split a dataset based on an attribute and an attribute value

def test_split(index, value, dataset):
    left, right = list(), list()
    for row in dataset:
        if row[index] < value:
            left.append(row)
        else:
            right.append(row)
    return left, right
	
# Calculate the Gini index for a split dataset
# Select the best split point for a dataset

def gini_index(groups, classes):
    n_instances = float(sum([len(group) for group in groups]))
    gini = 0.0
    for group in groups:
        size = float(len(group))
        if size == 0:
            continue
        score = 0.0
        for class_val in classes:
            p = [row[-1] for row in group].count(class_val) / size
            score += p * p
        gini += (1.0 - score) * (size / n_instances)
    return gini

def get_split(dataset):
    class_values = list(set(row[-1] for row in dataset))
    b_index, b_value, b_score, b_groups = 999, 999, 999, None
    for index in range(len(dataset[0])-1):
        for row in dataset:
            groups = test_split(index, row[index], dataset)
            gini = gini_index(groups, class_values)
            if gini < b_score:
                b_index, b_value, b_score, b_groups = index, row[index], gini, groups
    return {'index':b_index, 'value':b_value, 'groups':b_groups}

# Create a terminal node value
def to_terminal(group):
	outcomes = [row[-1] for row in group]
	return max(set(outcomes), key=outcomes.count)

# Create child splits for a node or make terminal
def split(node, max_depth, min_size, depth):
	left, right = node['groups']
	del(node['groups'])
	# check for a no split
	if not left or not right:
		node['left'] = node['right'] = to_terminal(left + right)
		return
	# check for max depth
	if depth >= max_depth:
		node['left'], node['right'] = to_terminal(left), to_terminal(right)
		return
	# process left child
	if len(left) <= min_size:
		node['left'] = to_terminal(left)
	else:
		node['left'] = get_split(left)
		split(node['left'], max_depth, min_size, depth+1)
	# process right child
	if len(right) <= min_size:
		node['right'] = to_terminal(right)
	else:
		node['right'] = get_split(right)
		split(node['right'], max_depth, min_size, depth+1)

# Build a decision tree
def build_tree(train, max_depth, min_size):
	root = get_split(train)
	split(root, max_depth, min_size, 1)
	return root

# Make a prediction with a decision tree
def predict(node, row):
	if row[node['index']] < node['value']:
		if isinstance(node['left'], dict):
			return predict(node['left'], row)
		else:
			return node['left']
	else:
		if isinstance(node['right'], dict):
			return predict(node['right'], row)
		else:
			return node['right']

# Final Decision Tree Algorithm
def print_tree(node, depth=0):
	if isinstance(node, dict):
		print('%s[X%d < %.3f]' % ((depth*' ', (node['index']+1), node['value'])))
		print_tree(node['left'], depth+1)
		print_tree(node['right'], depth+1)
	else:
		print('%s[%s]' % ((depth*' ', node)))
    
def decision_tree(train, test, max_depth, min_size):
    tree = build_tree(train, max_depth, min_size)
    print("Decision Tree this Fold \n \n")
    print_tree(tree)
    print("\n \n")
    predictions = list()
    for row in test:
        prediction = predict(tree, row)
        predictions.append(prediction)
    return(predictions)

# # Decision Tree call

n_folds = 4
max_depth = 5
min_size = 10
scores = evaluate_algorithm(all_data, decision_tree, n_folds, max_depth, min_size)
print('Decision Tree Scores: %s' % scores)
print('Decision Tree Mean of 4 Folds Accuracy: %.3f%%' % (sum(scores)/float(len(scores))))

Decision Tree this Fold 
 

[X3 < 4.000]
 [X5 < 126.000]
  [X8 < 97.000]
   [3.0]
   [X4 < 122.000]
    [X8 < 141.000]
     [1.0]
     [3.0]
    [X4 < 160.000]
     [2.0]
     [0.0]
  [X10 < 0.800]
   [X1 < 57.000]
    [X4 < 192.000]
     [0.0]
     [1.0]
    [X8 < 96.000]
     [1.0]
     [0.0]
   [X1 < 70.000]
    [X1 < 44.000]
     [0.0]
     [0.0]
    [3.0]
 [X1 < 60.000]
  [X9 < 1.000]
   [X5 < 160.000]
    [X10 < 1.600]
     [1.0]
     [2.0]
    [X13 < 6.000]
     [0.0]
     [1.0]
   [X13 < 6.000]
    [X7 < 1.000]
     [1.0]
     [1.0]
    [X8 < 135.000]
     [1.0]
     [2.0]
  [X4 < 120.000]
   [X10 < 2.000]
    [1.0]
    [2.0]
   [X10 < 1.800]
    [X2 < 1.000]
     [1.0]
     [2.0]
    [X8 < 102.000]
     [3.0]
     [3.0]

 

Decision Tree this Fold 
 

[X3 < 4.000]
 [X5 < 100.000]
  [X8 < 97.000]
   [3.0]
   [X4 < 122.000]
    [X10 < 0.000]
     [0.0]
     [1.0]
    [X8 < 111.000]
     [2.0]
     [0.0]
  [X1 < 57.000]
   [X10 < 0.600]
    [X4 < 192.000]
     [0.0]
     [1.0]
  

In [23]:
### Bayesian Classifier
def splitDataset(dataset, splitRatio):
    trainSize = int(len(dataset) * splitRatio)
    trainSet = []
    copy = list(dataset)
    while len(trainSet) < trainSize:
        index = random.randrange(len(copy))
        trainSet.append(copy.pop(index))
    return [trainSet, copy]

def separateByClass(dataset):
    separated = {}
    for i in range(len(dataset)):
        vector = dataset[i]
        if (vector[-1] not in separated):
            separated[vector[-1]] = []
        separated[vector[-1]].append(vector)
    return separated

def mean(numbers):
    return sum(numbers)/float(len(numbers))

def stdev(numbers):
    avg = mean(numbers)
    variance = sum([pow(x-avg,2) for x in numbers])/float(len(numbers)-1)
    return math.sqrt(variance)

def summarize(dataset):
    summaries = [(mean(attribute), stdev(attribute)) for attribute in zip(*dataset)]
    del summaries[-1]
    return summaries

def summarizeByClass(dataset):
    separated = separateByClass(dataset)
    summaries = {}
    for classValue, instances in separated.items():
        summaries[classValue] = summarize(instances)
    return summaries

def calculateProbability(x, mean, stdev):
    exponent = math.exp(-(math.pow(x-mean,2)/(2*math.pow(stdev,2))))
    return (1 / (math.sqrt(2*math.pi) * stdev)) * exponent

def calculateClassProbabilities(summaries, inputVector):
    probabilities = {}
    for classValue, classSummaries in summaries.items():
        probabilities[classValue] = 1
        for i in range(len(classSummaries)):
            mean, stdev = classSummaries[i]
            x = inputVector[i]
            probabilities[classValue] *= calculateProbability(x, mean, stdev)
    return probabilities

def predict(summaries, inputVector):
    probabilities = calculateClassProbabilities(summaries, inputVector)
    bestLabel, bestProb = None, -1
    for classValue, probability in probabilities.items():
        if bestLabel is None or probability > bestProb:
            bestProb = probability
            bestLabel = classValue
    return bestLabel

def getPredictions(summaries, testSet):
    predictions = []
    for i in range(len(testSet)):
        result = predict(summaries, testSet[i])
        predictions.append(result)
    return predictions

def getAccuracy(testSet, predictions):
    correct = 0
    for i in range(len(testSet)):
        if testSet[i][-1] == predictions[i]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0

# prepare model
summaries = summarizeByClass(X_train)
# test model
predictions = getPredictions(summaries, X_test)
accuracy = getAccuracy(X_test, predictions)
print("Bayesian Accuracy")
print(accuracy)

Bayesian Accuracy
53.2608695652174
